# Generated by Django 4.1.3 on 2023-02-10 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('dimension', models.CharField(max_length=255, verbose_name='Dimension')),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('last_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última modificación')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsable')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='box.dimension', verbose_name='Dimensión')),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.picking', verbose_name='Despacho')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-last_modification'],
            },
        ),
    ]
