# Generated by Django 4.1.6 on 2023-03-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
        ('picking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='picking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picking.picking', verbose_name='Despacho'),
        ),
    ]
