# Generated by Django 4.1.6 on 2023-03-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('saleorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.reference', verbose_name='Referencia')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorder.saleorder', verbose_name='Orden de venta')),
            ],
            options={
                'verbose_name': 'Articulo Solicitado',
                'verbose_name_plural': 'Articulos Solicitados',
                'ordering': ['-id'],
            },
        ),
    ]
