# Generated by Django 4.1.6 on 2023-02-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('item_code', models.CharField(max_length=100, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Referencia')),
                ('model_size', models.CharField(max_length=100, verbose_name='Talla')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['-id'],
            },
        ),
    ]
