# Generated by Django 4.1.6 on 2023-03-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PayTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Termino de pago',
                'verbose_name_plural': 'Terminos de pago',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('no_sale_order', models.CharField(max_length=20, verbose_name='No Orden de venta')),
                ('publication_date', models.DateField(verbose_name='Fecha publicación')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('doc_date', models.DateField(verbose_name='Fecha de documento')),
                ('po_comments', models.TextField(verbose_name='PO Comentarios')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Dirección de entrega')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorder.collection', verbose_name='Colección')),
                ('pay_term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorder.payterm', verbose_name='Término de pago')),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Ordenes de venta',
                'ordering': ['-id'],
            },
        ),
    ]
