# Generated by Django 4.1.6 on 2023-02-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='picking.statuspicking', verbose_name='Estado'),
        ),
    ]
