# Generated by Django 4.1.6 on 2023-03-09 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picking', '0001_initial'),
        ('saleorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='picking',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorder.saleorder', verbose_name='Orden de venta'),
        ),
        migrations.AddField(
            model_name='picking',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='picking.status', verbose_name='Estado'),
        ),
    ]
