# Generated by Django 4.1.6 on 2023-02-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0002_alter_picking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusPicking',
            new_name='Status',
        ),
    ]
